### ISSUE TITLE
Merge strategy for `antsibull*` project PRs

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/antsibull-core#114]
Currently, the `antsibull*` projects only allow squash merges. As discussed in https://github.com/ansible/ansible-documentation/issues/554, squash merges have some limitations. I'd like to enable rebases or merge commits in addition to squash merges that we can use to apply larger changes, such as the `antsibull-build verify-upstreams` one I'm working on. where each commit has its own semantic purpose and commit body that should be preserved. I had trouble git blaming that issue that caused https://github.com/ansible-community/antsibull/commit/e651c6dbb16aa933e36ca4e1a9cd170fd9dba7e0, as a larger change that had well thought out commits that were all squashed together was the culprit. We can add a `rebase_merge` or `merge_commit` label to add to changes that should be applied in this manner.

I'm not partial to either rebases or merges for the `antsibull*` projects [^1], but I think at least one should be enabled.

[^1]: I only insisted on enabling merge commits in the ansible-documentation repo, as we make heavy usage of patchback there that is incompatible with rebases.

**Comment by felixfontein** [comment]
I'm fine with enabling rebase merges.

One problem with rebase merges is that the patchback bot won't handle them correctly, but that shouldn't be a problem for the antsibull projects since they rarely use it. (And they usually use it for bugfixes which usually consist of one commit in `main`.)

**Comment by gotmax23** [comment]
I added `rebase_merge` labels and changed the settings for antsibull, antsibull-changelog, and antsibull-docs-parser. I don't have `maintainer` (only `write`) on antsibull-docs and antsibull-core, so I could not change the settings there. If you add me as a `maintainer`, I can do that, or you can :).

**Comment by felixfontein** [comment]
@gotmax23 I've given you `maintainer` rights and changed the settings (or at least enabled rebase merge, not sure what's more to change).

**Comment by gotmax23** [comment]
Cool. Thanks! Everything's sorted now.
