### ISSUE TITLE
[v3] Remove deprecated `GalaxyClient` contrstuctor default arguments

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/antsibull-core#121]

**Comment by felixfontein** [comment]
Hmm, these arguments haven't been deprecated yet.

**Comment by felixfontein** [comment]
I guess we can still remove them. We don't promise deprecations before removals (even for collections included in Ansible we suggest they do it, but don't enforce it), and the only two known users of antsibull-core don't need this anymore. This is a new major release, so let's just remove it anyway.

**Comment by felixfontein** [comment]
I've implemented this in #131. Some of this functionality is currently still used in antsibull-docs and antsibull, I've created PRs to make them stop using it.
