### ISSUE TITLE
[v3] Remove residual support for old ansible versions

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/antsibull-core#123]
antsibull only supports building ansible 6.0.0 releases, but antsibull-core still has residual code for building older ansible releases and for dealing with ansible-base. We should identify that code and remove it.

**Comment by felixfontein** [comment]
I think this mainly covers:

- ansible-base support;
- dependency files: `_acd_version` and `_ansible_base_version` in deps and build files; special cases while writing these files;

**Comment by gotmax23** [comment]
Right. I started working on this last night.

**Comment by felixfontein** [comment]
I mainly went through to get an idea of what this will be myself, since I could only come up with ansible-base when first thinking about this; I didn't intend to work on it (except in case you won't :) ).
