### ISSUE TITLE
Plan for antsibull-core v3

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/antsibull-core#125]
I created [a milestone](https://github.com/ansible-community/antsibull-core/milestone/2) and have started creating issues to track antsibull-core v3. My impetus for starting up this effort is wanting to add support for pydantic v2, but there's also a good amount deprecated code to remove. @felixfontein, what do you think about the following plan?

For antsibull-core v3, I'd like to completely drop support for pydantic v1 and stick to pydantic v2. antsibull-core v2 can stick to pydantic v3. Maintaining compatibility for both is a bit tricky, and parts of the pydantic API that are exposed/used by antsibull-core as part of the LibContext and AppContext objects are changing in a backwards compatible way, so we would probably want to add support in a new major release anyways.

We might consider dropping support for Python 3.9, as well, to allow us to adopt newer typing features and other improvements. ansible-core has already dropped support for Python 3.9 on the controller.

antsibull and antsibull-docs can keep concurrent support for both antsibull-core v2 and v3 for a little while, like we did for antsibull-core v1. I'm not sure about when we'd want to cut a antsibull-docs v3 release to drop support for antsibull-core v2. antsibull-docs is more your area than mine.

I think I'll be able to write some compat code for antsibull-docs to remain compatible with both pydantic versions (and thus both antsibull-core versions). I already submitted https://github.com/ansible-community/antsibull/pull/564 for antsibull. It uses LibContext and AppContext but doesn't have its own pydantic models, so that was easier.

**Comment by gotmax23** [comment]
Yeah, I'm fine with keeping Python 3.9 support for antsibull-core v3. I just put that option out there.

> I think I'll be able to write some compat code for antsibull-docs to remain compatible with both pydantic versions (and thus both antsibull-core versions). I already submitted [ansible-community/antsibull#564](https://github.com/ansible-community/antsibull/pull/564) for antsibull. It uses LibContext and AppContext but doesn't have its own pydantic models, so that was easier.

I submitted https://github.com/ansible-community/antsibull-docs/pull/224. I changed everything to use the `pydantic.v1` compat module (which is just a copy of the last pydantic v1 release included within pydantic v2's tree) for all models except AppContext which is inherited from antsibull-core. It's a bit messy and touches several files. I'd really prefer not to do this and just keep antsibull-docs v2 tied to antsibull-core v2 and properly port antsibull-docs v3 to pydantic v2, but I just wanted to put this out there.

What do you think?

**Comment by felixfontein** [comment]
Sounds good to me!

**Comment by gotmax23** [comment]
@felixfontein, you mean

> keep antsibull-docs v2 tied to antsibull-core v2 and properly port antsibull-docs v3 to pydantic v2

or that we should attempt to maintain compatibility between antsibull-docs v2 and antsibull-core v3 as in https://github.com/ansible-community/antsibull-docs/pull/224?

**Comment by felixfontein** [comment]
Ah sorry, yes, I meant making it compatible to both core v2 and v3. I'd lke to avoid doing a new major release for some time...

**Comment by gotmax23** [comment]
I created a `stable-2` branch and filed the following PRs:

- https://github.com/ansible-community/antsibull/pull/567
- https://github.com/ansible-community/antsibull-docs/pull/230
- https://github.com/ansible-community/antsibull-core/pull/127

**Comment by gotmax23** [comment]
@felixfontein, what do you think about creating a 3.0.0a1 release later this week?

**Comment by felixfontein** [comment]
@gotmax23 sounds good to me! If you have time, can you take a look at #135? Would be nice to get that one in as well.

**Comment by gotmax23** [comment]
We can cut the release after https://github.com/ansible-community/antsibull-core/pull/144 is reviewed and merged.

**Comment by felixfontein** [comment]
So, how should we proceed? Should we do 3.0.0 final soon?

**Comment by gotmax23** [comment]
Yes, I think so!

**Comment by felixfontein** [comment]
antsibull-core 3.0.0 is out! \o/ The remaining task is to eventually limit the minimum antsibull and antsibull-docs versions supporting 3.0.0 in CI; I've created #154 to track this.
