### ISSUE TITLE
Port to `sh` v2 or ditch it entirely

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/antsibull-core#34]
Currently, we pin `sh` to `>= 1.0.0 < 2.0.0`, due to breaking changes. We should port antsibull to the new version or make our code compatible with both.

(Another option would be to ditch it altogether and just use `subprocess.run` or a helper function. I prefer to avoid extra dependencies when possible. Maybe sh is worth keeping, but I will note that it's not compatible with static analysis tools (we need to add pylint ignores every time) which causes some headache.))

**Comment by felixfontein** [comment]
I'm currently tending to ditch `sh` completely. While it doesn't have transitive dependencies, every removed dependency is a good one IMO ;)

**Comment by felixfontein** [comment]
(antsibull-core 2.x.y needs to keep `sh >= 1.0.0 < 2.0.0` to avoid breakage with antsibull and antsibull-docs releases that claim compatibility with antsibull-core 2.x.y. But we can still stop using it, and plan removal for 3.0.0.)

**Comment by gotmax23** [comment]
I think I'll propose an `antsibull_core.subprocess_utils` module that has a `run()` (sync) and `async_run()` (async) function. They'll behave like `subprocess.run` but will always log stderr (`flog.debug()` by default).

**Comment by felixfontein** [comment]
There's also an async version of subprocess: https://docs.python.org/3/library/asyncio-subprocess.html This might be useful for some use-cases as well.

**Comment by gotmax23** [comment]
We have merged

- https://github.com/ansible-community/antsibull-core/commit/0388c0fa5a284b3317da83e6f9ecdb2795619aa9 - add subprocess_util module to replace sh
- https://github.com/ansible-community/antsibull-core/commit/39a435608c3f10e976e55d81f0178f4389aa3fae - venv: prepare for sh removal and add tests
- https://github.com/ansible-community/antsibull-core/commit/28f969c4e7b83675d3fdbef84eba82f75514ee14 - replace remaining usage of sh with subprocess_util
- https://github.com/ansible-community/antsibull-core/commit/886bcc7e92cd14247ae090772286c0883ae92dae - Allow to handle UTF-8 decoding errors
- https://github.com/ansible-community/antsibull-core/commit/d910be2ec7f521160cba57d9f1d74b59e4596346 - Work around line length limit of asyncio.StreamReader

so we can close this, right?

**Comment by felixfontein** [comment]
Not really, antsibull-core still needs to be depending on sh until 3.0.0 (for backwards compatibility with certain older antsibull/antsibull-docs releases). I would keep this open until then.
