### ISSUE TITLE
Add support for pydantic v2

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/antsibull-core#92]
As of https://github.com/ansible-community/antsibull-core/commit/03a2882514572cfeeea676dd07f9bcc606d61956, we restricted pydantic to v1. Now that pydantic v2 is GA, we should fix any incompats, relax this pin, and make sure to test with both versions in CI.

**Comment by felixfontein** [comment]
The migration guide will be helpful: https://docs.pydantic.dev/2.0/migration/

**Comment by gotmax23** [comment]
This shouldn't be *too* difficult, but we'll have to silence some DeprecationWarnings while we're still supporting pydantic v1.  I'm not sure what to do about https://github.com/ansible-community/antsibull-core/blob/be1492762e3111530759c1ada6764f73694dfde8/src/antsibull_core/schemas/context.py#L63 though. The way pydantic v2 handles extra arguments is a bit different.
